// @generated by remix/assets — do not edit manually
// source: app/entry.tsx
const entryTsxAsset = {
  href: '/__@assets/app/entry.tsx',
  preloads: ['/__@assets/app/entry.tsx#preloads'],
}
export default entryTsxAsset
