// @generated by remix/assets — do not edit manually
// source: app/worker.ts
const workerTsAsset = {
  href: '/__@assets/app/worker.ts',
  preloads: ['/__@assets/app/worker.ts#preloads'],
}
export default workerTsAsset
