allowBuilds:
  '@swc/core': true
  esbuild: true
  sharp: true
  workerd: true

catalog:
  '@types/hast': 3.0.5
  '@types/node': ^24.6.0
  '@typescript/native-preview': 7.0.0-dev.20260707.2
  github-slugger: 2.0.0
  oxfmt: ^0.51.0
  pagefind: 1.5.2
  playwright: ^1.60.0
  shiki: 4.4.1
  typescript: ^7.0.2

packages:
  - demos/*
  - docs/api
  - docs/guides
  - docs/shared
  - docs/shared/prerender/bench
  - packages/*
  - packages/*/demo
  - packages/assets/bench
  - packages/cli/test/fixtures/*
  - packages/data-schema/bench
  - packages/fetch-router/demos/*
  - packages/form-data-parser/demos/*
  - packages/ui/bench
  - packages/ui/bench/frameworks/*
  - packages/lazy-file/scripts
  - packages/multipart-parser/bench
  - packages/multipart-parser/demos/*
  - packages/node-fetch-server/bench
  - packages/node-fetch-server/demos/*
  - packages/route-pattern/bench
  - packages/tar-parser/bench
  - template
  - scripts

shellEmulator: true
