packages:
  - packages/*
  - packages/form-data-parser/examples/*
  - packages/multipart-parser/bench
  - packages/multipart-parser/examples/*
  - packages/node-fetch-server/bench
  - packages/tar-parser/bench
  - scripts
