packages:
  - "integration"
  - "integration/helpers/node-template"
  - "integration/helpers/cf-template"
  - "integration/helpers/deno-template"
  - "integration/helpers/vite-cloudflare-template"
  - "integration/helpers/vite-template"
  - "packages/create-remix"
  - "packages/remix"
  - "packages/remix-architect"
  - "packages/remix-cloudflare"
  - "packages/remix-cloudflare-pages"
  - "packages/remix-cloudflare-workers"
  - "packages/remix-css-bundle"
  - "packages/remix-deno"
  - "packages/remix-dev"
  - "packages/remix-eslint-config"
  - "packages/remix-express"
  - "packages/remix-fs-routes"
  - "packages/remix-node"
  - "packages/remix-react"
  - "packages/remix-route-config"
  - "packages/remix-routes-option-adapter"
  - "packages/remix-serve"
  - "packages/remix-server-runtime"
  - "packages/remix-testing"
