#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

type ScriptDefinition = {
  exportName: string
  fileName: string
}

let scriptDefinitions: ScriptDefinition[] = [
  { exportName: 'ENQUEUE_JOB_SCRIPT', fileName: 'enqueue-job.lua' },
  { exportName: 'CANCEL_JOB_SCRIPT', fileName: 'cancel-job.lua' },
  { exportName: 'CLAIM_DUE_JOBS_SCRIPT', fileName: 'claim-due-jobs.lua' },
  { exportName: 'HEARTBEAT_JOB_SCRIPT', fileName: 'heartbeat-job.lua' },
  { exportName: 'COMPLETE_JOB_SCRIPT', fileName: 'complete-job.lua' },
  { exportName: 'FAIL_JOB_SCRIPT', fileName: 'fail-job.lua' },
  { exportName: 'LIST_FAILED_JOBS_SCRIPT', fileName: 'list-failed-jobs.lua' },
  { exportName: 'RETRY_FAILED_JOB_SCRIPT', fileName: 'retry-failed-job.lua' },
  { exportName: 'PRUNE_JOBS_SCRIPT', fileName: 'prune-jobs.lua' },
]

let scriptDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../src/lib/lua')
let outputFile = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../src/lib/generated-lua.ts')
let command = 'pnpm --filter @remix-run/job-redis run generate:scripts'

function main(): void {
  let generated = buildGeneratedModule()
  let checkOnly = process.argv.includes('--check')

  if (checkOnly) {
    let current = ''

    try {
      current = normalizeContents(readFileSync(outputFile, 'utf8'))
    } catch {
      throw new Error(`Generated Lua scripts are missing. Run \`${command}\`.`)
    }

    if (current !== generated) {
      throw new Error(`Generated Lua scripts are out of date. Run \`${command}\`.`)
    }

    return
  }

  writeFileSync(outputFile, generated)
}

function buildGeneratedModule(): string {
  let lines = [
    '// This file is generated by packages/job-redis/scripts/generate-lua.ts.',
    '// It is committed so tests can run from source without a build step.',
    `// Do not edit it by hand. Run \`${command}\` to update it.`,
    '',
  ]

  for (let definition of scriptDefinitions) {
    let source = readLuaFile(definition.fileName)
    lines.push(`export const ${definition.exportName} = ${JSON.stringify(source)}`)
  }

  lines.push('')

  return lines.join('\n')
}

function readLuaFile(fileName: string): string {
  return normalizeContents(readFileSync(path.join(scriptDir, fileName), 'utf8'))
}

function normalizeContents(contents: string): string {
  return contents.replace(/\r\n/g, '\n')
}

main()
