import {
  callComponentRenderForHmr,
  clearComponentHmrState,
  getComponentHandleForHmr,
  getComponentHmrState,
  getCurrentComponentForHmr,
  registerComponentForHmr,
  registerComponentInstanceForHmr,
  registerComponentRenderForHmr,
  setupComponentForHmr,
  updateComponentModuleForHmr,
} from '../lib/browser-runtime.ts'

/**
 * Browser component-refresh operations called by code generated by `component-hmr` transforms.
 *
 * This is an internal protocol surface for transformed modules, not an application API.
 */
export const __componentHmrBrowserRuntime__ = {
  callComponentRenderForHmr,
  clearComponentHmrState,
  getComponentHandleForHmr,
  getComponentHmrState,
  getCurrentComponentForHmr,
  registerComponentForHmr,
  registerComponentInstanceForHmr,
  registerComponentRenderForHmr,
  setupComponentForHmr,
  updateComponentModuleForHmr,
}
