import { getCurrentComponentForHmr, registerComponentForHmr } from '../lib/server-runtime.ts'

/**
 * Server component-refresh operations called by code generated by `component-hmr` transforms.
 *
 * This is an internal protocol surface for transformed modules, not an application API.
 */
export const __componentHmrServerRuntime__ = {
  getCurrentComponentForHmr,
  registerComponentForHmr,
}
