blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request
    url: https://github.com/remix-run/remix/discussions/new?category=proposals
    about: If you've got an idea for a new feature in Remix, please open a new Discussion with the `Proposals` label
  - name: 💬 Remix Discord Channel
    url: https://remix.run/discord
    about: Interact with other people using Remix 📀
  - name: 🤔 Usage Question (Github Discussions)
    url: https://github.com/remix-run/remix/discussions/new?category=q-a
    about: Open a Discussion in GitHub with the `Q&A` label
