import { type KVNamespace } from "@cloudflare/workers-types";

// In the future, types for bindings will be generated by `wrangler types`
// See https://github.com/cloudflare/workers-sdk/pull/4931
type Bindings = {
  // Add types for bindings configured in `wrangler.toml`
  MY_KV: KVNamespace;
};

declare module "@remix-run/cloudflare" {
  interface AppLoadContext {
    env: Bindings;
  }
}
