// @generated by remix/assets — do not edit manually
// source: app/assets/cart-button.tsx
export const href = '/__@assets/app/assets/cart-button.tsx'
export const preloads = ['/__@assets/app/assets/cart-button.tsx#preloads']
