// @generated by remix/assets — do not edit manually
// source: app/assets/cart-button.tsx
const cartButtonTsxAsset = {
  href: '/__@assets/app/assets/cart-button.tsx',
  preloads: ['/__@assets/app/assets/cart-button.tsx#preloads'],
}
export default cartButtonTsxAsset
