// @generated by remix/assets — do not edit manually
// source: app/assets/cart-items.tsx
export const href = '/__@assets/app/assets/cart-items.tsx'
export const preloads = ['/__@assets/app/assets/cart-items.tsx#preloads']
