// @generated by remix/assets — do not edit manually
// source: app/assets/cart-items.tsx
const cartItemsTsxAsset = {
  href: '/__@assets/app/assets/cart-items.tsx',
  preloads: ['/__@assets/app/assets/cart-items.tsx#preloads'],
}
export default cartItemsTsxAsset
