// @generated by remix/assets — do not edit manually
// source: app/assets/image-carousel.tsx
export const href = '/__@assets/app/assets/image-carousel.tsx'
export const preloads = ['/__@assets/app/assets/image-carousel.tsx#preloads']
