// @generated by remix/assets — do not edit manually
// source: app/assets/image-carousel.tsx
export const href = '/app/assets/image-carousel.tsx'
export const preloads = ['/app/assets/image-carousel.tsx']
