// @generated by remix/assets — do not edit manually
// source: app/assets/image-carousel.tsx
const imageCarouselTsxAsset = {
  href: '/__@assets/app/assets/image-carousel.tsx',
  preloads: ['/__@assets/app/assets/image-carousel.tsx#preloads'],
}
export default imageCarouselTsxAsset
