#:schema node_modules/wrangler/config-schema.json
name = "remix-cloudflare-workers"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"

[build]
  command = "npm run build"

[assets]
directory = "./public"

[observability]
# Set this to true to enable logging. (Extra costs may apply)
# https://developers.cloudflare.com/workers/observability/logs/workers-logs
enabled = false
