import { bench } from '@ark/attest'

import type { Params } from './params.ts'

// Simple benchmark: Basic route patterns with single features
bench('Params - Small', () => {
  return {} as Params<'users/:id'>
}).types([1430, 'instantiations'])

// Medium benchmark: Moderate complexity with combined features (~10 patterns)
bench('Params - Medium', () => {
  return {} as Params<
    | 'api/v:version/users/:id'
    | 'blog/:year/:month/:slug'
    | 'files/*path.:ext'
    | 'shop/new/products/:id'
    | 'users/:id(/:action)'
    | 'en/blog/:category'
    | 'api/users/:id/*attachments'
    | 'cdn/:version/*asset.js'
    | '(/:locale)/products/:category'
    | 'admin/users/:id/edit'
  >
}).types([22081, 'instantiations'])

// Large/Complex benchmark: 100 route patterns with various feature combinations
bench('Params - Large', () => {
  return {} as Params<
    | 'home'
    | ':slug'
    | '*'
    | '*files'
    | '{home,about,contact}'
    | '(/:lang)'
    | 'users/:id'
    | 'posts/*path'
    | 'api/v1'
    | 'files(/:id)'
    | 'admin/users/:id/edit'
    | 'blog/:year/:month/:day'
    | 'shop/products/:category/*'
    | 'en/about'
    | 'api/v:version/users'
    | 'files/*path.:ext'
    | '(/:locale)/home'
    | 'users/:id(/:action)'
    | 'posts/:slug.{html,json}'
    | 'api/users/:id/*path'
    | '{admin,user}/dashboard'
    | 'blog/:year(/:month)'
    | 'shop/new/items'
    | 'files/:id.:format'
    | '(/:lang)/products/:id'
    | 'api/v:version/*endpoint'
    | 'users/:id/{edit,delete}'
    | 'posts/:slug(.:format)'
    | 'cdn/*path.js'
    | '{blog,news}/:year/:slug'
    | 'api/(v:version/){users,posts}'
    | 'uploads/:user/*file.:ext'
    | '(/:locale)/home'
    | 'admin/users/:id(/:tab)'
    | 'blog/:year/:month(/:day)'
    | 'shop/category/:name/*items'
    | 'files/:folder/*path.:type'
    | 'api/v:version/auth'
    | 'users/:id/posts(/:slug)'
    | 'cdn/:version/*asset.{js,css}'
    | '(/:lang)/shop/men'
    | 'api/users/:id/profile'
    | 'blog/:category/:year/:slug'
    | 'uploads/*path.:format'
    | 'en/blog/:slug'
    | 'api/v:version/users/:id/*'
    | 'files/:user/:folder/*name'
    | '(/:locale)/products/:category'
    | 'admin/users/:id/edit'
    | 'blog/:year/:month/:day/:slug'
    | 'shop/products/:id(.:format)'
    | 'cdn/*path.{min.js,min.css}'
    | 'api/v:version/auth/:token'
    | 'users/:id/posts/:slug(/:action)'
    | 'uploads/:year/:month/*file.:ext'
    | '(/:lang)/blog/:category'
    | 'api/users/:id/posts/*'
    | 'files/:user/:project/*path.:type'
    | 'admin/posts/:id/:action'
    | 'blog/:category/:year/:month/:slug'
    | 'shop/men/:category/*items'
    | 'cdn/:version/*asset.js'
    | '(/:locale)/shop/products/:id/reviews'
    | 'api/v:version/users/:id/posts(/:slug)'
    | 'uploads/:user/:year/:month/*file'
    | 'en/blog/:category/:slug'
    | 'admin/users/:id/profile'
    | 'files/:org/:project/:branch/*path.:ext'
    | '(/:lang)/shop/men/:category'
    | 'api/v1/users/:id/posts/*path'
    | 'blog/:year/:month/:day/:slug.:format'
    | 'cdn/*path.js'
    | 'api/v:version/auth/login'
    | 'users/:id/posts/:slug/edit'
    | 'uploads/:user/:project/*file.jpg'
    | '(/:locale)/blog/:category/:year'
    | 'api/v:version/users/:id/posts/:item'
    | 'files/:org/:repo/:branch/*path.ts'
    | 'admin/posts/:id/:action'
    | 'blog/:category/:subcategory/:year/:slug'
    | 'shop/men/:category/:subcategory/*'
    | 'cdn/:env/*asset.{min.js,min.css,woff2}'
    | '(/:lang)/shop/products/:category/:id'
    | 'api/v1/users/:id/posts(/:slug)'
    | 'uploads/:org/:user/:year/*file.:format'
    | 'en/blog/:category/:slug'
    | 'admin/users/:id/profile'
    | 'files/:org/:project/:env/*path.ts'
    | '(/:locale)/shop/men/:category/:id'
    | 'api/v:version/users/:id/posts/:slug/comments/*'
    | 'https://example.com/api/v:version/users/:id'
    | ':protocol://example.com/path/:id'
    | 'https://:subdomain.example.com/api/*path'
    | ':protocol://:host:port/api/v:version/*'
    | 'https://api.example.com:8080/v:version/users/:id'
    | ':protocol://:subdomain.example.com:port/api/*path.:format'
  >
}).types([228435, 'instantiations'])
