import { bench } from '@ark/attest'

import type { Params } from './params.ts'

// Simple benchmark: Basic route patterns with single features
bench('Params - Small', () => {
  return {} as Params<'users/:id'>
}).types([1346, 'instantiations'])

// Medium benchmark: Moderate complexity with combined features (~10 patterns)
bench('Params - Medium', () => {
  // @ts-expect-error - This is a benchmark
  return {} as Params<
    | 'api/v:version/users/:id'
    | 'blog/:year/:month/:slug'
    | 'files/*path.:ext'
    | 'shop/{new,sale}/products/:id'
    | 'users/:id(/:action)'
    | '{en,fr}/blog/:category'
    | 'api/users/:id/*attachments'
    | 'cdn/:version/*asset.{js,css}'
    | '(/:locale)/products/:category'
    | 'admin/{users,posts}/:id/edit'
  >
}).types([5012937, 'instantiations'])

// Large/Complex benchmark: 100 route patterns with various feature combinations
bench('Params - Large', () => {
  return {} as Params<
    | 'home'
    | ':slug'
    | '*'
    | '*files'
    | '{home,about,contact}'
    | '(/:lang)'
    | 'users/:id'
    | 'posts/*path'
    | 'api/{v1,v2}'
    | 'files(/:id)'
    | 'admin/users/:id/edit'
    | 'blog/:year/:month/:day'
    | 'shop/products/:category/*'
    | '{en,fr}/about'
    | 'api/v:version/users'
    | 'files/*path.:ext'
    | '(/:locale)/home'
    | 'users/:id(/:action)'
    | 'posts/:slug.{html,json}'
    | 'api/users/:id/*path'
    | '{admin,user}/dashboard'
    | 'blog/:year(/:month)'
    | 'shop/{new,sale}/items'
    | 'files/:id.:format'
    | '(/:lang)/products/:id'
    | 'api/v:version/*endpoint'
    | 'users/:id/{edit,delete}'
    | 'posts/:slug(.:format)'
    | 'cdn/*path.{js,css,png}'
    | '{blog,news}/:year/:slug'
    | 'api/(v:version/){users,posts}'
    | 'uploads/:user/*file.:ext'
    | '(/:locale)/{home,about}'
    | 'admin/users/:id(/:tab)'
    | 'blog/:year/:month(/:day)'
    | 'shop/category/:name/*items'
    | 'files/:folder/*path.:type'
    | '{api,web}/v:version/auth'
    | 'users/:id/posts(/:slug)'
    | 'cdn/:version/*asset.{js,css}'
    | '(/:lang)/shop/{men,women}'
    | 'api/users/:id/{profile,settings}'
    | 'blog/:category/:year/:slug'
    | 'uploads/*path.:format'
    | '{en,es,fr}/blog/:slug'
    | 'api/v:version/users/:id/*'
    | 'files/:user/:folder/*name'
    | '(/:locale)/products/:category'
    | 'admin/{users,posts}/:id/edit'
    | 'blog/:year/:month/:day/:slug'
    | 'shop/products/:id(.:format)'
    | 'cdn/*path.{min.js,min.css}'
    | '{api,app}/v:version/auth/:token'
    | 'users/:id/posts/:slug(/:action)'
    | 'uploads/:year/:month/*file.:ext'
    | '(/:lang)/{blog,news}/:category'
    | 'api/users/:id/{posts,comments}/*'
    | 'files/:user/:project/*path.:type'
    | '{admin,editor}/posts/:id/:action'
    | 'blog/:category/:year/:month/:slug'
    | 'shop/{men,women}/:category/*items'
    | 'cdn/:version/*asset.{js,css,woff}'
    | '(/:locale)/shop/products/:id/reviews'
    | 'api/v:version/users/:id/posts(/:slug)'
    | 'uploads/:user/:year/:month/*file'
    | '{en,es,fr,de}/blog/:category/:slug'
    | 'admin/users/:id/{profile,settings,permissions}'
    | 'files/:org/:project/:branch/*path.:ext'
    | '(/:lang)/shop/{men,women}/:category'
    | 'api/{v1,v2}/users/:id/posts/*path'
    | 'blog/:year/:month/:day/:slug.:format'
    | 'cdn/*path.{js,css,png,jpg,svg}'
    | '{api,web}/v:version/auth/{login,logout}'
    | 'users/:id/posts/:slug/{edit,delete,publish}'
    | 'uploads/:user/:project/*file.{jpg,png,gif}'
    | '(/:locale)/{blog,news}/:category/:year'
    | 'api/v:version/users/:id/{posts,comments}/:item'
    | 'files/:org/:repo/:branch/*path.:type'
    | '{admin,editor,viewer}/posts/:id/:action'
    | 'blog/:category/:subcategory/:year/:slug'
    | 'shop/{men,women}/:category/:subcategory/*'
    | 'cdn/:env/*asset.{min.js,min.css,woff2}'
    | '(/:lang)/shop/products/:category/:id'
    | 'api/{v1,v2,v3}/users/:id/posts(/:slug)'
    | 'uploads/:org/:user/:year/*file.:format'
    | '{en,es,fr,de,it}/blog/:category/:slug'
    | 'admin/users/:id/{profile,settings,permissions,audit}'
    | 'files/:org/:project/:env/*path.{js,ts}'
    | '(/:locale)/shop/{men,women}/:category/:id'
    | 'api/v:version/users/:id/posts/:slug/{comments,likes,shares}/*'
    | 'https://example.com/api/v:version/users/:id'
    | ':protocol://example.com/path/:id'
    | 'https://:subdomain.example.com/api/*path'
    | ':protocol://:host:port/api/v:version/*'
    | 'https://api.example.com:8080/v:version/users/:id'
    | ':protocol://:subdomain.example.com:port/api/*path.:format'
  >
}).types([6727, 'instantiations'])
