const MOBILE_NAV_BREAKPOINT = 980
export const MOBILE_TOP_BAR_HEIGHT = 48
export const MOBILE_NAV_MAX_VIEWPORT_HEIGHT = 0.85
export const MOBILE_NAV_MAX_HEIGHT_OFFSET = MOBILE_TOP_BAR_HEIGHT + 8
export const MOBILE_TOP_BAR_HEIGHT_PX = `${MOBILE_TOP_BAR_HEIGHT}px`
export const MOBILE_NAV_MEDIA_QUERY = `(max-width: ${MOBILE_NAV_BREAKPOINT}px)`
export const MOBILE_NAV_MEDIA_RULE = `@media ${MOBILE_NAV_MEDIA_QUERY}`
export const MOBILE_NAV_MAX_HEIGHT = `calc(${MOBILE_NAV_MAX_VIEWPORT_HEIGHT * 100}vh - ${MOBILE_NAV_MAX_HEIGHT_OFFSET}px)`
