import { checkCodegenPlaceholders } from '@remix-run/assets'
import { buildConfig } from './assets.ts'

let result = await checkCodegenPlaceholders({ source: buildConfig.source })

if (result.missing.length > 0) {
  console.error('Missing generated files:', result.missing)
}
if (result.stale.length > 0) {
  console.error('Stale generated files (no matching source):', result.stale)
}
if (result.outdated.length > 0) {
  console.error('Outdated generated files:', result.outdated)
}
if (result.unknown.length > 0) {
  console.error('Unexpected files in .assets/ (not generated by codegen):', result.unknown)
}

let total =
  result.missing.length + result.stale.length + result.outdated.length + result.unknown.length
if (total > 0) {
  console.error(`\nRun "pnpm codegen" to fix. (${total} issue${total === 1 ? '' : 's'})`)
  process.exit(1)
}

console.log('Asset placeholder files are up to date.')
