// @generated by remix/assets — do not edit manually
// source: app/images/books/bbq-1.png
export const href = '/__@assets/app/images/books/bbq-1.png?@card'
export const variants = {
  thumbnail: { href: '/__@assets/app/images/books/bbq-1.png?@thumbnail' },
  card: { href: '/__@assets/app/images/books/bbq-1.png?@card' },
  hero: { href: '/__@assets/app/images/books/bbq-1.png?@hero' },
}
