// @generated by remix/assets — do not edit manually
// source: app/images/books/heavy-metal-1.png
const heavyMetal1PngAsset = {
  href: '/__@assets/app/images/books/heavy-metal-1.png?@card',
  variants: {
    thumbnail: { href: '/__@assets/app/images/books/heavy-metal-1.png?@thumbnail' },
    card: { href: '/__@assets/app/images/books/heavy-metal-1.png?@card' },
    hero: { href: '/__@assets/app/images/books/heavy-metal-1.png?@hero' },
  },
}
export default heavyMetal1PngAsset
