// @generated by remix/assets — do not edit manually
// source: app/images/books/three-ways-1.png
export const href = '/__@files/app/images/books/three-ways-1.png?@card'
export const variants = {
  thumbnail: { href: '/__@files/app/images/books/three-ways-1.png?@thumbnail' },
  card: { href: '/__@files/app/images/books/three-ways-1.png?@card' },
  hero: { href: '/__@files/app/images/books/three-ways-1.png?@hero' },
}
