name: Debug Windows test failures

on:
  push:
    branches:
      - markdalgleish/debug-windows-test-failures

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_ubuntu:
    name: test (ubuntu-latest, full suite)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install Node.js
        uses: ./.github/actions/setup-node-pnpm-cache

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get Playwright Version
        id: playwright-version
        shell: bash
        run: echo "version=$(pnpm --filter @remix-run/ui exec playwright --version | cut -d ' ' -f2)" >> $GITHUB_OUTPUT

      - name: Cache Playwright Browsers
        id: cache-browsers
        uses: actions/cache@v5
        continue-on-error: true
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright Browsers
        if: steps.cache-browsers.outputs.cache-hit != 'true'
        run: pnpm --filter @remix-run/ui exec playwright install --with-deps

      - name: Run tests
        run: pnpm --parallel --filter "!remix-the-web" run test

  test_windows:
    name: test (windows-latest, full suite)
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install Node.js
        uses: ./.github/actions/setup-node-pnpm-cache

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get Playwright Version
        id: playwright-version
        shell: bash
        run: echo "version=$(pnpm --filter @remix-run/ui exec playwright --version | cut -d ' ' -f2)" >> $GITHUB_OUTPUT

      - name: Cache Playwright Browsers
        id: cache-browsers
        uses: actions/cache@v5
        continue-on-error: true
        with:
          path: ~/AppData/Local/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright Browsers
        if: steps.cache-browsers.outputs.cache-hit != 'true'
        run: pnpm --filter @remix-run/ui exec playwright install --with-deps

      - name: Run tests
        run: pnpm --workspace-concurrency=16 --no-sort --filter "!remix-the-web" run test
