name: 👔 Format

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORMAT_PAT }}

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: 📥 Install deps
        run: pnpm install --frozen-lockfile

      - name: 🔗 Convert Docs links to references
        run: node scripts/markdown-references.mjs

      - name: 🔃 Sort contributors.yml
        run: sort --ignore-case --output contributors.yml contributors.yml

      - name: 👔 Format
        run: pnpm format

      - name: 🦕 Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: 👔 Format Deno files
        run: pnpm format:deno

      - name: 💪 Commit
        run: |
          git config --local user.email "hello@remix.run"
          git config --local user.name "Remix Run Bot"

          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "💿 no formatting changed"
            exit 0
          fi
          git commit -m "chore: format"
          git push
          echo "💿 pushed formatting changes https://github.com/$GITHUB_REPOSITORY/commit/$(git rev-parse HEAD)"
